### ISSUE TITLE
unable to run

### ISSUE THREAD

**Issue by therovermind** [saisandeepvaddi/movie-search-react#1]
file /home/ankur/Downloads/movie-search-react-master/package.json
npm ERR! code EJSONPARSE
npm ERR! Failed to parse json
npm ERR! Unexpected end of input at 22:2
npm ERR! 
npm ERR! ^
npm ERR! File: /home/ankur/Downloads/movie-search-react-master/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! Tell the package author to fix their package.json file. JSON.parse

hi there, i removed three lines in package.json and cant run the app

**Comment by saisandeepvaddi** [comment]
Hi,
Can I see your package.json ?
